### ISSUE TITLE
Support multiple runners on the same VM

### ISSUE THREAD

**Issue by RunsFor** [MonolithProjects/ansible-github_actions_runner#39]
Thanks, this projects helped me quickly bootstrap a runner for my project and get going.

However, I quickly realised, I need to have multiple runners on the same VM instance. In fact, [it is possible to do](https://github.community/t/how-to-run-multiple-self-hosted-runners-on-a-single-host/130474/2) with github runner.

I'm going to implement this myself. Can make a PR. What do you think? Seems, variable structure may change a bit.

**Comment by MonolithProjects** [comment]
Hi there... happy to hear it helped you.
Since it is not recommended to run more runner services on single system, i would not add this feature to this Ansible Role. 
BTW if you need to run several runners on one VM, i guess you should look for dockerized GitHub Runner. It could be a better solution.
