### ISSUE TITLE
Custom service names appear to be broken

### ISSUE THREAD

**Issue by mwhite-ibm** [MonolithProjects/ansible-github_actions_runner#74]
I was attempting to install a runner on a GitHub Enterprise 3.0 instance, with `github_owner` set to our GitHub org (in the example below, `test-org`) and `runner_name` set to `ansible_host` (`test-runner`).

I noticed that despite `svc.sh install` succeeding, the service could not start:
```
FAILED! => {"changed": false, "msg": "Could not find the requested service actions.runner.a-test-org.test-runner.service: host"}
```

I noticed the file `actions.runner._services.test-runner.service` getting written to `/etc/systemd/system` instead.

Upon further inspection of the Actions runner source code, I found that it has a [hardcoded service name template](https://github.com/actions/runner/blob/main/src/Runner.Listener/Configuration/SystemdControlManager.cs#L16), where `{0}` is subbed with the [`repoOrOrgName` derived from the runner settings](https://github.com/actions/runner/blob/main/src/Runner.Listener/Configuration/ServiceControlManager.cs#L50). Looking at `.runner` on my runner machine, I see `https://<GHE_SERVER>/_services/...` for `serverUrl` ([which `repoOrOrgName` is based on](https://github.com/actions/runner/blob/main/src/Runner.Common/ConfigurationStore.cs#L68)), so it makes sense why `_services` is making its way into the service name.

I also tried with `service_name` explicitly set to `test-service` and the same thing happened.

Overall, it would appear that org-derived and custom service names are broken (at least for Enterprise). We were able to get by this by just using `service_name: "actions.runner._services.{{ runner_name }}.service"`.

Perhaps the solution here is to move the service file to match the configured service name after `svc.sh install` finishes?

Thanks, and by the way this is an amazing repo!

**Comment by MonolithProjects** [comment]
Hi @mwhite-ibm , thanks for info! I will look into this (probably today or tomorrow)

**Comment by MonolithProjects** [comment]
Hi @mwhite-ibm, i am unable to simulate your issue. Can you confirm that you are using the latest role release? (1.8.2)

**Comment by mwhite-ibm** [comment]
@MonolithProjects Oh interesting!

Yep, we're using the most recent version of the role.
```
➤ ansible-galaxy list
...
- monolithprojects.github_actions_runner, 1.8.2
```

At the top of my `svc.sh` script:
```
SVC_NAME="actions.runner._services.<RUNNER_NAME>.service"
```

Where `<RUNNER_NAME>` is the string we specified via `runner_name`.

And for the service file:
```
[Unit]
Description=GitHub Actions Runner (_services.<RUNNER_NAME>)
After=network.target

[Service]
ExecStart=/opt/actions-runner/runsvc.sh
User=<RUNNER_USER>
WorkingDirectory=/opt/actions-runner
KillMode=process
KillSignal=SIGTERM
TimeoutStopSec=5min

[Install]
WantedBy=multi-user.target
```

`<RUNNER_USER>` is what we specified via `runner_user`.

**Comment by Th0masL** [comment]
I can confirm that we cannot set custom services names, or at least not for SystemD on Ubuntu20.

I'm using the following variable:
```
service_name: "github_actionsrunner"
```

And then I have the same error as above :
```
TASK [monolithprojects.github_actions_runner : START and enable Github Actions Runner service] **************************************************************************
fatal: [gharunner.hiv.layer0-dev.co]: FAILED! => {"changed": false, "msg": "Could not find the requested service github_actionsrunner: host"}
```

I will try to troubleshoot why there's this problem

**Comment by Th0masL** [comment]
Basically it looks like the problem comes from the content of the file `svc.sh` (the file .service was containing the correct service_name).

I don't know exactly how the file `svc.sh` is generated, but the `SVC_NAME` in this file does not match the `service_name` passed in the vars.

I was able to bypass this issue by adding a task that replace the value of `SVC_NAME` in `svc.sh`.

In `install_runner.yml`, just before the task named `Install service`, add this task :

```
- name: Update the service name in the svc.sh file because we can't pass the value dynamically
  lineinfile:
    path: "{{ runner_dir }}/svc.sh"
    line: 'SVC_NAME="{{ runner_service }}.service"'
    regexp: "^SVC_NAME=.actions"
    insertbefore: "^SVC_DESCRIPTION="
```

I doubt it's the right way to fix the problem, but so far it's working.

I have the feeling that the problem comes from the way the `SVC` variable is populated in the file `svc.sh`.

This `svc.sh` file is created by some scripts in the official [actions/runner](https://github.com/actions/runner/) code, so we won't be able to fix this problem nicely, unless we find a way to update the [actions/runner](https://github.com/actions/runner/) code.

**Comment by MonolithProjects** [comment]
@mwhite-ibm @Th0masL Sorry for late response.

Starting with [1.12.0](https://github.com/MonolithProjects/ansible-github_actions_runner/tree/1.12.0) I deprecated `service_name: "actions.runner._services.{{ runner_name }}.service"`  since i guess it was not clear enough why and how it should be used :) Instead of this, if you are using GH Enterprise Server, you just need to set `running_on_ghes: true` and the service name generated in the ansible role will match the service name on the system.

**Comment by mwhite-ibm** [comment]
@MonolithProjects Gotcha, thanks for the update!

**Comment by mwhite-ibm** [comment]
FYI, minor doc PR related to these changes: https://github.com/MonolithProjects/ansible-github_actions_runner/pull/106.

**Comment by MonolithProjects** [comment]
Cool, thanks!
